from .base import BaseStrategy, BacktestResult, Signal
from .strategy_collection import (
    ColorsStrategy,
    RSILawStrategy,
    EMAEngulfingStrategy,
    MACrossoverStrategy,
    PriceActionStrategy,
    SupportResistanceStrategy,
    FibonacciStrategy,
    MomentumStrategy,
    PullbackStrategy,
    ScalpingStrategy,
    BreakoutStrategy,
    NewsTradingStrategy,
    SwingTradingStrategy,
    RSIDivergenceStrategy,
    TrendFollowingStrategy,
    RejectionCandleStrategy,
    LadderPatternStrategy,
    RetracementPatternStrategy,
    CandleParityStrategy,
    MicrostructureStrategy,
    ChangePointStrategy,
)

ALL_STRATEGIES = [
    ColorsStrategy(),
    RSILawStrategy(),
    EMAEngulfingStrategy(),
    MACrossoverStrategy(),
    PriceActionStrategy(),
    SupportResistanceStrategy(),
    FibonacciStrategy(),
    MomentumStrategy(),
    PullbackStrategy(),
    ScalpingStrategy(),
    BreakoutStrategy(),
    NewsTradingStrategy(),
    SwingTradingStrategy(),
    RSIDivergenceStrategy(),
    TrendFollowingStrategy(),
    RejectionCandleStrategy(),
    LadderPatternStrategy(),
    RetracementPatternStrategy(),
    CandleParityStrategy(),
    MicrostructureStrategy(),
    ChangePointStrategy(),
]

__all__ = ["BaseStrategy", "BacktestResult", "Signal", "ALL_STRATEGIES"]
